apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f2axfb66l-java-springboot
  janus-idp.io/tekton: f2axfb66l-java-springboot
  backstage.io/kubernetes-id: f2axfb66l-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f2axfb66l-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
